language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get -q install gfortran libatlas-base-dev libatlas-dev liblapack-dev
install:
- pip install ghp-import
- pip install .
- rm -r src/testfm
script:
- nosetests -vv
after_success:
- cd docs
- make publish
env:
  global:
  - secure: dMa5sKLUi7mjp4YHVj0YTVj4wZ+S+zUWKhPrWA30HpOPzd+s9BoV3fXU30x4Qc+fM/h8CYrtzDe8EZUdwRKNk/2jlIn6fou4UGoO081rRgNwPeKivpOo0uR7iuywyCHJJFQroUaWcJugJn55XtKMYxr0owwAjqI9z5fp4xMytA4=
